### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by johnrichardrinehart** [reblGreen/DimWin-Brightness#2]
# Not Technically an "Issue"

Regardless of setting, my laptop screen is too bright. I wanted a small binary that I could install that would add brightness control to the taskbar. I was hoping someone would have designed one with some kind of shadow overlay feature so that I could dim beyond the limits of the brightness keys on my keyboard: Lo and behold!

This medicine is exactly what the doctor ordered. Great job and thank you!

Installing and becoming satisfied took ~50 seconds (most of the bottleneck was network I/O..... slow internet).

Oh, small question: "sudo" brightness refers to the top slider in your screenshot and in the application, right?

**Comment by johnearnshaw** [comment]
Thanks, I'm glad you find DimWin useful. Yes that is correct, in this case sudo (a short form of the word "pseudo", meaning fake) refers to the fake brightness feature of DimWin.

**Comment by johnrichardrinehart** [comment]
Perfect. Again, great job.
